#-----------------------------------------------------------------------------------------------------------------------------------
# Copyright (c) 2008-2022 Base2 Incorporated--All Rights Reserved.
#-----------------------------------------------------------------------------------------------------------------------------------
#DEBUG: require_dependency "#{Base2Cvb::Engine.root}/lib/models/seed"
require_dependency "#{Base2Cms::Engine.root}/app/models/seed"

class Seed
  def self.set_defaults_application(parent_tagmap)
    prospect = Tagmap.find_tagmap_creating_if_needed('Meeting Status', 'meeting_status', 'Prospect', 'meeting_status_prospect')
    definite = Tagmap.find_tagmap_creating_if_needed('Meeting Status', 'meeting_status', 'Definite', 'meeting_status_definite')
    tentative = Tagmap.find_tagmap_creating_if_needed('Meeting Status', 'meeting_status', 'Tentative', 'meeting_status_tentative')
    lost = Tagmap.find_tagmap_creating_if_needed('Meeting Status', 'meeting_status', 'Lost', 'meeting_status_lost')

    definite.position = 47; definite.save!
    tentative.position = 48; tentative.save!
    prospect.position = 49; prospect.save!
    lost.position = 50; lost.save!

    Tagmap.find_tagmap_creating_if_needed('View Type', 'view_type', 'Calculations', 'view_type_calculations')

    Tagmap.find_tagmap_creating_if_needed('Spending Event Type', 'spending_event_type', 'Amateur Youth', 'spending_event_type_amateur_youth')
    Tagmap.find_tagmap_creating_if_needed('Spending Event Type', 'spending_event_type', 'Amateur Adult', 'spending_event_type_amateur_adult')
    Tagmap.find_tagmap_creating_if_needed('Spending Event Type', 'spending_event_type', 'Professional / College', 'spending_event_type_professional_college')

    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Sports Indiana Grant', 'meeting_date_category_sports_indiana_grant')

    #NOTE: added per james 11/14/2017
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Youth State', 'meeting_date_category_amateur_youth_state')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Youth Regional', 'meeting_date_category_amateur_youth_regional')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Youth National', 'meeting_date_category_amateur_youth_national')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Youth World', 'meeting_date_category_amateur_youth_world')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Adult State', 'meeting_date_category_amateur_adult_state')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Adult Regional', 'meeting_date_category_amateur_adult_regional')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Amateur Adult National', 'meeting_date_category_amateur_adult_national')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'College/Pro State', 'meeting_date_category_college_pro_state')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'College/Pro Regional', 'meeting_date_category_college_pro_regional')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'College/Pro National', 'meeting_date_category_college_pro_national')
    Tagmap.find_tagmap_creating_if_needed('Meeting Date Category', 'meeting_date_category', 'Other', 'meeting_date_category_other')

    if ConstantValue.context_scope.where(:label => 'economics_settings').all.size == 0
      year = Time.now.year

      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccequipmentmargin', '.25')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccfoodandbeveragemargin', '.18')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccinternetmargin', '.75')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'cclaborreimbursementmargin', '.28')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccothermargin', '.05')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead0', '.0376')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead1', '.0376')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead10', '.0181')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead11', '.0181')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead2', '.0376')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead3', '.0187')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead4', '.0187')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead5', '.0187')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead6', '.02596')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead7', '.02596')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead8', '.02596')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccoverhead9', '.0181')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccspacerentalmargin', '1.00')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'ccutilitiesmargin', '.1')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsfederalrate', '.110534755647346')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsjobsdirect', '0.0000102861031900')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsjobsindirect', '0.0000028336528116')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsjobsinduced', '0.0000024532691975')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationslocalrate', '.020341420014205')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsstaterate', '.0233940241345158')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsvadirect', '0.5935333082438270')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsvaindirect', '0.2086417267895570')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationsvainduced', '0.1799391941345010')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationswagesdirect', '0.2484639992134880')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationswagesindirect', '0.1284938728245900')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'conventionoperationswagesinduced', '0.1038705786450820')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobsairtraffic', '0.000003479504')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobsentertainment', '0.000008731645')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobsfood', '0.000015956728')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobsroom', '0.000010330582')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobsshopping', '0.000016220855')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directjobstransport', '0.000010700044')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvaairtraffic', '0.335232073647')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvaentertainment', '0.531449123305')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvafood', '0.467967473776')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvaroom', '0.570645891188')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvashopping', '0.634810786893')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directvatransport', '0.593569057382')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagesairtraffic', '0.256796369557')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagesentertainment', '0.365648712561')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagesfood', '0.315368590603')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagesroom', '0.318908287151')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagesshopping', '0.426469637290')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'directwagestransport', '0.299837394995')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'entity1breakdowndebt', '.66')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'entity1breakdownoperations', '.34')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsairtraffic', '0.04640834335')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsentertainment', '0.03723989021')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsfood', '0.09475374849')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsother', '0.00000201792')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsroom', '0.00024077894')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobsshopping', '0.07226553070')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectjobstransport', '0.06399058756')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvaairtraffic', '0.04640834353')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvaentertainment', '0.03102556047')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvafood', '0.09475374930')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvaother', '0.18712232742')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvaroom', '0.00024077894')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvashopping', '0.19683246343')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectvatransport', '0.09195483546')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesairtraffic', '0.04640834398')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesentertainment', '0.03616433506')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesfood', '0.09475374896')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesother', '0.11110230517')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesroom', '0.00024077893')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagesshopping', '0.17308154234')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'indirectwagestransport', '0.11980889980')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsairtraffic', '0.077976527044')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsentertainment', '0.085904420471')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsfood', '0.115371162665')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsother', '0.000001912905')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsroom', '0.000409161222')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobsshopping', '0.456192563308')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedjobstransport', '0.052891361672')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvaairtraffic', '0.077976527339')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvaentertainment', '0.076009508191')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvafood', '0.115371163649')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvaother', '0.176311996333')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvaroom', '0.000409161216')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvashopping', '0.679835525638')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedvatransport', '0.068340920318')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesairtraffic', '0.077976528106')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesentertainment', '0.064160570924')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesfood', '0.115371163233')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesother', '0.094657029116')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesroom', '0.000409161210')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagesshopping', '0.619836510846')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inducedwagestransport', '0.071779858708')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'inflation', '.0125')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingairtraffic', '.07')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingentertainment', '.10')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingfood', '.10')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingother', '.07')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingroom', '.17')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingshopping', '.07')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'netspendingtransport', '.08448')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingairtraffic', '7.77')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingairtraffic.738268', '7.77')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingairtraffic.738269', '7.77')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingairtraffic.738270', '7.77')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingentertainment', '23.46')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingentertainment.738268', '23.46')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingentertainment.738269', '23.46')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingentertainment.738270', '23.46')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingfood', '44.57')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingfood.738268', '44.57')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingfood.738269', '44.57')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingfood.738270', '44.57')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingroom', '116.27')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingroom.738268', '116.27')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingroom.738269', '116.27')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingroom.738270', '116.27')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingshopping', '24.51')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingshopping.738268', '24.51')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingshopping.738269', '24.51')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingshopping.738270', '24.51')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingtransport', '24.76')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingtransport.738268', '24.76')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingtransport.738269', '24.76')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'spendingtransport.738270', '24.76')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax10categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax10label', 'Sales Taxes')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax10localrate', '0.0013655405347451')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax10staterate', '0.0836971615456207')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax11categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax11federalrate', '0.0604180957659983')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax11label', 'Social Security & Other Taxes')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax1categories', 'E[0.5]')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax1label', 'Admissions Tax')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax2categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax2federalrate', '0.0130829990994494')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax2label', 'Corporate Income')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax2staterate', '0.0069293968059522')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax3categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax3federalrate', '0.0150982133347278')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax3label', 'Excise & Fees')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax3localrate', '0.0039422616534012')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax3staterate', '0.0016129829490083')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax4categories', 'R')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax4entity1rate', '.07')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax4entity2rate', '.03')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax4label', 'Hotel Tax')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax4localrate', '.10')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax5categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax5label', 'Other Business Taxes')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax5staterate', '0.0016129829490083')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax6categories', 'ATFRSEOG')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax6federalrate', '0.0346839991684838')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax6label', 'Personal Income')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax6localrate', '0.0013825167770650')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax6staterate', '0.0096776174394549')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax8categories', 'T[.362]G[.362]')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax8entity1rate', '.02')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax8entity2rate', '.02')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax8label', 'Rental Car Tax')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax8localrate', '.04')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax9categories', 'F')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax9entity1rate', '.02')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax9entity2rate', '.01')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax9label', 'Food & Beverage Tax')
      ConstantValue.find_value_creating_if_needed('economics_settings', year, 'tax9localrate', '.03')
    end
  end
end
