class MeetingDateChangeIncomeCommissionType < ActiveRecord::Migration[6.0]
  def change
    change_column :meeting_date_financial_commitments, :income_commission, :text
    change_column :extended_meeting_dates, :financial_commitment_income_commission, :text

    execute "update meeting_date_financial_commitments set income_commission='' where income_commission='0.00';"
    execute "update meeting_date_financial_commitments set income_commission='1%' where income_commission='0.01';"
    execute "update meeting_date_financial_commitments set income_commission='2%' where income_commission='0.02';"
    execute "update meeting_date_financial_commitments set income_commission='3%' where income_commission='0.03';"
    execute "update meeting_date_financial_commitments set income_commission='4%' where income_commission='0.04';"
    execute "update meeting_date_financial_commitments set income_commission='5%' where income_commission='0.05';"
    execute "update meeting_date_financial_commitments set income_commission='6%' where income_commission='0.06';"
    execute "update meeting_date_financial_commitments set income_commission='7%' where income_commission='0.07';"
    execute "update meeting_date_financial_commitments set income_commission='8%' where income_commission='0.08';"
    execute "update meeting_date_financial_commitments set income_commission='9%' where income_commission='0.09';"
    execute "update meeting_date_financial_commitments set income_commission='10%' where income_commission='0.10';"
    execute "update meeting_date_financial_commitments set income_commission='11%' where income_commission='0.11';"
    execute "update meeting_date_financial_commitments set income_commission='12%' where income_commission='0.12';"
    execute "update meeting_date_financial_commitments set income_commission='13%' where income_commission='0.13';"
    execute "update meeting_date_financial_commitments set income_commission='14%' where income_commission='0.14';"
    execute "update meeting_date_financial_commitments set income_commission='15%' where income_commission='0.15';"
    execute "update meeting_date_financial_commitments set income_commission='16%' where income_commission='0.16';"
    execute "update meeting_date_financial_commitments set income_commission='17%' where income_commission='0.17';"
    execute "update meeting_date_financial_commitments set income_commission='18%' where income_commission='0.18';"
    execute "update meeting_date_financial_commitments set income_commission='19%' where income_commission='0.19';"
    execute "update meeting_date_financial_commitments set income_commission='20%' where income_commission='0.20';"

    execute "update extended_meeting_dates set financial_commitment_income_commission='' where financial_commitment_income_commission='0.00';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='1%' where financial_commitment_income_commission='0.01';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='2%' where financial_commitment_income_commission='0.02';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='3%' where financial_commitment_income_commission='0.03';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='4%' where financial_commitment_income_commission='0.04';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='5%' where financial_commitment_income_commission='0.05';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='6%' where financial_commitment_income_commission='0.06';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='7%' where financial_commitment_income_commission='0.07';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='8%' where financial_commitment_income_commission='0.08';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='9%' where financial_commitment_income_commission='0.09';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='10%' where financial_commitment_income_commission='0.10';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='11%' where financial_commitment_income_commission='0.11';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='12%' where financial_commitment_income_commission='0.12';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='13%' where financial_commitment_income_commission='0.13';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='14%' where financial_commitment_income_commission='0.14';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='15%' where financial_commitment_income_commission='0.15';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='16%' where financial_commitment_income_commission='0.16';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='17%' where financial_commitment_income_commission='0.17';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='18%' where financial_commitment_income_commission='0.18';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='19%' where financial_commitment_income_commission='0.19';"
    execute "update extended_meeting_dates set financial_commitment_income_commission='20%' where financial_commitment_income_commission='0.20';"
  end
end
